// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using calendarDDD.Infrastructure;

namespace calendarDDD.Infrastructure.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("calendarDDD.Domain.AggregateModels.UserAggregate.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TeamEntity");
                });

            modelBuilder.Entity("calendarDDD.Domain.AggregateModels.UserAggregate.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("UserEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc781a75-9cf3-49b9-b273-80c577bd2ba3"),
                            PreName = "Hans",
                            SurName = "Müller"
                        },
                        new
                        {
                            Id = new Guid("20ff1e9b-cf1d-4dd1-ac43-f0a0568b336f"),
                            PreName = "Maria",
                            SurName = "Schmidt"
                        },
                        new
                        {
                            Id = new Guid("63b8cd3d-0000-4f22-8eb0-c46833c647e4"),
                            PreName = "Peter",
                            SurName = "Fischer"
                        });
                });

            modelBuilder.Entity("calendarDDD.Domain.AggregateModels.UserAggregate.UserEntity", b =>
                {
                    b.HasOne("calendarDDD.Domain.AggregateModels.UserAggregate.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
